repos:
  - repo: local
    hooks:
      - id: pre-push-django-makemigrations
        stages: [push]
        name: Check django migrations
        entry: python manage.py makemigrations --check --dry-run
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args: ["--score=n"]
        require_serial: false
        additional_dependencies: []