# Generated by Django 3.2.6 on 2021-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
