# Generated by Django 3.2.7 on 2021-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_booklist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('travel_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'destinamtion',
            },
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'etc',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'romms',
            },
        ),
        migrations.DeleteModel(
            name='Booklist',
        ),
    ]
