# Generated by Django 3.2.7 on 2021-10-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211005_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='second',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='tag_secodne',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
