# Generated by Django 3.2.7 on 2021-10-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211006_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='tag_secodne',
            new_name='tag_second',
        ),
    ]
